name: 🚀 Generate README.md

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: 🎉 Deployment
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Specify your Node.js version here

      - name: Install NPM dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Configure Git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add README.md
          git commit -m "Auto updated README.md" || echo "No changes to commit"
          git push origin main
